### PR TITLE
New logo

### PR DESCRIPTION
**Pull request by heraldofsolace**
New logo requested by @Jimut123

### CODE REVIEW

**Comment by Jimut123** [comment]
I owe you another coke, @heraldofsolace

**Comment by sarvottamananda** [comment]
Welcome Aniket

I have merged it into develop. I am adding tutorial cs7 on reflections on spherical surfaces, I will upgrade the develop into master then. 

Now I am trying to follow gitflow workflow strictly, rather than following my own model and explaining it to everyone. This way we have a standard to follow even if it is not perfect. 
See the link below for quick understanding
https://datasift.github.io/gitflow/IntroducingGitFlow.html#:~:text=GitFlow%20is%20a%20branching%20model,and%20scaling%20the%20development%20team.

It misses the bugfix branches.
For bugfix branches we have the cheat sheet https://danielkummer.github.io/git-flow-cheatsheet/

There are also support branches for support teams.

In my local computer I work on feature branches. I do not push those to github. (So, you do not get to see my bad code :-) ) Right now I am working on feature branch named feature/cs7 with ver 0.7

After this course is over, we will directly go to 1.0 version and go into maintenance mode.

Aniket, if you can, can you draw a mascot for all our projects. That can be used again and again with variations. For example, https://www.google.com/search?q=mascot+golang&tbm=isch&ved=2ahUKEwje1aXpm4ztAhWTzXMBHeUjB6gQ2-cCegQIABAA&oq=mascot+golang&gs_lcp=CgNpbWcQAzICCAAyBggAEAUQHjIGCAAQCBAeOgQIIxAnOgUIABCxAzoECAAQHlDLOljDTGDQTWgAcAB4AIABqQGIAc0KkgEDMC45mAEAoAEBqgELZ3dzLXdpei1pbWfAAQE&sclient=img&ei=CSS1X56tPJObz7sP5cecwAo&bih=977&biw=1920

**Comment by sarvottamananda** [comment]
@Aniket, use svg vector graphics format, so that images are scalable.

**Comment by heraldofsolace** [comment]
@sarvottamananda 

> Aniket, if you can, can you draw a mascot for all our projects. 

Happily!

> @aniket, use svg vector graphics format, so that images are scalable.

I do have the svg versions too. Also, wrong username :)

**Pull request merged**
